spring:
  mail:
    username: 2231973602@qq.com # 发送者的邮箱，必须是QQ邮箱
    password: dspwtwceobsfeafa # 发送者邮箱的授权码，我将这个服务关闭了
---
pet-ship:
  images-path: /home/mixjade/mySoft/MixPet/images/ # 照片存储路径
  notice-path: /home/mixjade/mySoft/MixPet/notice/ # 公告存储路径
  chatImg-path: /home/mixjade/mySoft/MixPet/chatImg/ # 聊天图片存储路径