# -Dspring.profiles.active=local
spring:
  mail:
    username: 2231973602@qq.com # 发送者的邮箱，必须是QQ邮箱
    password: LocalLocalLocal # 发送者邮箱的授权码，我将这个服务关闭了
---
pet-ship:
  images-path: C:\MyCode\MixPet\images\ # 照片存储路径
  notice-path: C:\MyCode\MixPet\notice\ # 公告存储路径
  chatImg-path: C:\MyCode\MixPet\chatImg\ # 聊天图片存储路径
---
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印sql语句